[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://cashgrow-backend-api-481768223121.northamerica-northeast2.run.app"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
